### PR TITLE
Add Server Service archetype

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?

Add archetype for Che & Codenvy assembly based on Che ServerService sample:

selection_159

Structure looks as following:

- assembly-che (assembly for Che)
- assembly-codenvy (assembly for Codenvy)
- plugin (sample plugin, divided into client and server submodules)

Server side part, which has sample service `MyService`, which is mapped to path `"hello"` and serves GET methods, returns message `"Hello X!"`, where X would be the any path parameter to this service, e.g. "hello/user". Service is bound via `ServerServiceGuiceModule`

IDE Client-side part contains `ServerServiceExtension`, that registers action `MyAction`. which will be accessible in the main context menu (right-click in Project Explorer to open context menu), that calls this service by path `"hello/CheTheAllPowerful"`, and displays response in a notification ("Hello, CheTheAllPowerful!"). `MyServiceClient` contains all logic, regarding to calling the service.

Assemblies contain repackagings of assembly-ide-war for IDE GWT client-side, and assembly-wsagent-war/assembly-wsagent-server for server side of the plugin.

### What issue does this PR fix or reference?
https://github.com/eclipse/che-archetypes/issues/32

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@TylerJewell @JamesDrummond @bmicklea  We are introducing new che/codenvy samples. Is this description https://github.com/eclipse/che-archetypes/pull/36#issue-211358451 enough?

**Comment by TylerJewell** [comment]
@skabashnyuk - explanations look good.  You can assume that I'll handle all reviews for anything related to archetypes, so no need to include james or brad.

Question - are these the samples that we currently have on the docs?  We are just repackaging it as an assembly?

Question - can someone push a branch update into the CLI branch to add this example into the list of archetypes available, or is that for me to do?  If for me, then it's not clear the artifactId of this new archetype.

**Comment by mkuznyetsov** [comment]
@TylerJewell 
1 - This sample sources are simply copied from here (and added some archetype-related changes): https://github.com/eclipse/che/tree/master/samples/sample-plugin-serverservice. 
This is what if found in the Docs, that describes that sample in detail: https://www.eclipse.org/che/docs/plugins/serverworkspace-access/index.html

2 - I'll make a commit for your CLI branch and link it here

**Comment by TylerJewell** [comment]
That is great - we can convert each of the samples into an archetype and that way we do not lose that work.  Perfect.

**Comment by skabashnyuk** [comment]
@TylerJewell are we good to merge?

**Comment by TylerJewell** [comment]
After the CLI branch has commit linked here, +1 for merge.

**Comment by mkuznyetsov** [comment]
@TylerJewell here is that commit 
https://github.com/eclipse/che/commit/cadef9e0f191a57ec7741838b1ecf2629dd139b0

**Comment by TylerJewell** [comment]
Ok +1 for merging this PR

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
